package com.guima.domain;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ad", "id", Ad.class);
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("config", "id", Config.class);
		arp.addMapping("dictionary", "id", Dictionary.class);
		arp.addMapping("interface_config", "id", InterfaceConfig.class);
		arp.addMapping("plan", "id", Plan.class);
		arp.addMapping("plan_annex", "id", PlanAnnex.class);
		arp.addMapping("plan_comment", "id", PlanComment.class);
		arp.addMapping("plan_detail", "id", PlanDetail.class);
		arp.addMapping("plan_detail_annex", "id", PlanDetailAnnex.class);
		arp.addMapping("score_record", "id", ScoreRecord.class);
		arp.addMapping("sign", "id", Sign.class);
		arp.addMapping("user", "id", User.class);
	}
}

