package com.guima.domain;

import com.guima.domain.BaseActivity;
import com.guima.kits.Constant;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Activity extends BaseActivity<Activity> {
	public static final Activity dao = new Activity();

	public void init(String name, String createrId, String createrType, String activityType, String area1
	, String area2, String area3, String areaDesc, Date holdTime, String musicTheme, String desc,
					BigDecimal musicPrice, BigDecimal insertMusicPrice,Integer sameTimes, String logo,
					String status,String manualName){
		this.setName(name);
		this.setCreaterId(createrId);
		this.setCreaterType(createrType);
		this.setActivityType(activityType);
		this.setArea1(area1);
		this.setArea2(area2);
		this.setArea3(area3);
		this.setAreaDesc(areaDesc);
		this.setHoldTime(holdTime);
		this.setMusicTheme(musicTheme);
		this.setDesc(desc);
		this.setMusicPrice(musicPrice);
		this.setInsertMusicPrice(insertMusicPrice);
		this.setSameTimes(sameTimes);
		this.setLogo(logo);
		this.setStatus(status);
		this.setManualName(manualName);
	}

	public boolean addFriendsNum(){
		this.setFriendsNum(getFriendsNum()+1);
		return this.update();
	}

	public void addVideosNum(){
		this.setVideosNum(getVideosNum()+1);
	}

}
