package com.guima.domain;

import com.guima.domain.BaseActivityVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityVideo extends BaseActivityVideo<ActivityVideo> {

	public static final ActivityVideo dao = new ActivityVideo();

	public void init(String userId,String activityId,String videoId,String status,String playStatus,String playIdx,String insertType){
		this.setActivityId(activityId);
		this.setVideoId(videoId);
		this.setStatus(status);
		this.setPlayStatus(playStatus);
		this.setPlayIdx(playIdx);
		this.setInsertType(insertType);
		this.setUserId(userId);
	}
}
