package com.guima.domain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActivityUsers extends BaseActivityUsers<ActivityUsers> {
	public static final ActivityUsers dao = new ActivityUsers();

	public void init(String activityId,String userId,String status){
		this.setActivityId(activityId);
		this.setUserId(userId);
		this.setStatus(status);
		this.setInsertNum(0);
		this.setSuperInsertNum(0);
	}
}
