package com.guima.domain;

import com.guima.domain.BaseAdminExceptionRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminExceptionRecord extends BaseAdminExceptionRecord<AdminExceptionRecord> {
	public static final AdminExceptionRecord dao = new AdminExceptionRecord();
}
