package com.guima.domain;

import com.guima.domain.BaseAdvice;
import com.guima.kits.Constant;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advice extends BaseAdvice<Advice> {
	public static final Advice dao = new Advice();

	public void init(String creatorHeaderUrl, String creator, String creatorName, String content){
		setCreatorHeaderUrl(creatorHeaderUrl);
		setCreator(creator);
		setCreatorName(creatorName);
		setAdviceContent(content);
		setIsDeleted(Constant.IS_DELETED_NO);
		setCreateTime(new Date());
		setReply("");
	}
}
