package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVideo<M extends BaseModule<M>> extends BaseModule<M> {

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSingerId(java.lang.String singerId) {
		set("singer_id", singerId);
	}

	public java.lang.String getSingerId() {
		return get("singer_id");
	}

	public void setSingerName(java.lang.String singerName) {
		set("singer_name", singerName);
	}

	public java.lang.String getSingerName() {
		return get("singer_name");
	}

	public void setMusicTheme(java.lang.String musicTheme) {
		set("music_theme", musicTheme);
	}

	public java.lang.String getMusicTheme() {
		return get("music_theme");
	}

	public void setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
	}

	public java.lang.String getVideoUrl() {
		return get("video_url");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setHotIndex(java.lang.Integer hotIndex) {
		set("hot_index", hotIndex);
	}

	public java.lang.Integer getHotIndex() {
		return get("hot_index");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setLastChangeTime(java.util.Date lastChangeTime) {
		set("last_change_time", lastChangeTime);
	}

	public java.util.Date getLastChangeTime() {
		return get("last_change_time");
	}

}
