package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlan<M extends BasePlan<M>> extends BaseModule<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setPrivacy(java.lang.String privacy) {
		set("privacy", privacy);
	}

	public java.lang.String getPrivacy() {
		return get("privacy");
	}

	public void setCategory(java.lang.String category) {
		set("category", category);
	}

	public java.lang.String getCategory() {
		return get("category");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Integer getIsDeleted() {
		return get("is_deleted");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setLikeNum(java.lang.Integer likeNum) {
		set("like_num", likeNum);
	}

	public java.lang.Integer getLikeNum() {
		return get("like_num");
	}

	public void setParticipantNum(java.lang.Integer participantNum) {
		set("participant_num", participantNum);
	}

	public java.lang.Integer getParticipantNum() {
		return get("participant_num");
	}

	public void setFinishNum(java.lang.Integer finishNum) {
		set("finish_num", finishNum);
	}

	public java.lang.Integer getFinishNum() {
		return get("finish_num");
	}

	public void setUnFinishNum(java.lang.Integer unFinishNum) {
		set("un_finish_num", unFinishNum);
	}

	public java.lang.Integer getUnFinishNum() {
		return get("un_finish_num");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setIsOfficial(java.lang.Integer isOfficial) {
		set("is_official", isOfficial);
	}

	public java.lang.Integer getIsOfficial() {
		return get("is_official");
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public void setExeTimes(java.lang.Integer exeTimes) {
		set("exe_times", exeTimes);
	}

	public java.lang.Integer getExeTimes() {
		return get("exe_times");
	}

}
