package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanComment<M extends BasePlanComment<M>> extends BaseModule<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public void setCreatorId(java.lang.String creatorId) {
		set("creator_id", creatorId);
	}

	public java.lang.String getCreatorId() {
		return get("creator_id");
	}

	public void setCreatorName(java.lang.String creatorName) {
		set("creator_name", creatorName);
	}

	public java.lang.String getCreatorName() {
		return get("creator_name");
	}

	public void setCreatorHeaderUrl(java.lang.String creatorHeaderUrl) {
		set("creator_header_url", creatorHeaderUrl);
	}

	public java.lang.String getCreatorHeaderUrl() {
		return get("creator_header_url");
	}

	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}

	public java.lang.Integer getIsDeleted() {
		return get("is_deleted");
	}

	public void setPlanId(java.lang.String planId) {
		set("plan_id", planId);
	}

	public java.lang.String getPlanId() {
		return get("plan_id");
	}

}
