package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.guima.kits.DateKit;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivityUsers<M extends BaseModule<M>> extends BaseModule<M> {

	public void setActivityId(java.lang.String activityId) {
		set("activity_id", activityId);
	}

	public java.lang.String getActivityId() {
		return get("activity_id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setInsertNum(java.lang.Integer insertNum) {
		set("insert_num", insertNum);
	}

	public java.lang.Integer getInsertNum() {
		return get("insert_num");
	}

	public void setSuperInsertNum(java.lang.Integer superInsertNum) {
		set("super_insert_num", superInsertNum);
	}

	public java.lang.Integer getSuperInsertNum() {
		return get("super_insert_num");
	}

	public void setSuperTime(java.lang.String superTime) {
		set("super_time", superTime);
	}

	public java.lang.String getSuperTime() {
		return get("super_time");
	}

	public void setPlainTime(java.lang.String plainTime) {
		set("plain_time", plainTime);
	}

	public java.lang.String getPlainTime() {
		return get("plain_time");
	}

	/**
	 * 能否超级点歌 能 true
	 * @return
     */
	public boolean canAddSuperVideo(){
		String date= DateKit.curDate();
		//上一次点歌也在当天
		if(date.equals(this.getSuperTime())){
			return this.getSuperInsertNum()<3;
		}
		return true;
	}

	/**
	 * 能否普通点歌 能 true
	 * @return
	 */
	public boolean canAddPlainVideo(){
		String date= DateKit.curDate();
		//上一次点歌也在当天
		if(date.equals(this.getPlainTime())){
			return this.getInsertNum()<5;
		}
		return true;
	}

}
