package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.guima.kits.Kit;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.util.UUID;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean{

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id")==null?"":Integer.toString(get("id"));
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("creater_id", createrId);
	}

	public java.lang.String getCreaterId() {
		return get("creater_id");
	}

	public void setCreaterType(java.lang.String createrType) {
		set("creater_type", createrType);
	}

	public java.lang.String getCreaterType() {
		return get("creater_type");
	}

	public void setActivityType(java.lang.String activityType) {
		set("activity_type", activityType);
	}

	public java.lang.String getActivityType() {
		return get("activity_type");
	}

	public void setArea1(java.lang.String area1) {
		set("area1", area1);
	}

	public java.lang.String getArea1() {
		return get("area1");
	}

	public void setArea2(java.lang.String area2) {
		set("area2", area2);
	}

	public java.lang.String getArea2() {
		return get("area2");
	}

	public void setArea3(java.lang.String area3) {
		set("area3", area3);
	}

	public java.lang.String getArea3() {
		return get("area3");
	}

	public void setAreaDesc(java.lang.String areaDesc) {
		set("area_desc", areaDesc);
	}

	public java.lang.String getAreaDesc() {
		return get("area_desc");
	}

	public void setHoldTime(java.util.Date holdTime) {
		set("hold_time", holdTime);
	}

	public java.util.Date getHoldTime() {
		return get("hold_time");
	}

	public void setMusicTheme(java.lang.String musicTheme) {
		set("music_theme", musicTheme);
	}

	public java.lang.String getMusicTheme() {
		return get("music_theme");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setMusicPrice(java.math.BigDecimal musicPrice) {
		set("music_price", musicPrice);
	}

	public java.math.BigDecimal getMusicPrice() {
		return get("music_price");
	}

	public void setInsertMusicPrice(java.math.BigDecimal insertMusicPrice) {
		set("insert_music_price", insertMusicPrice);
	}

	public java.math.BigDecimal getInsertMusicPrice() {
		return get("insert_music_price");
	}

	public void setSameTimes(java.lang.Integer sameTimes) {
		set("same_times", sameTimes);
	}

	public java.lang.Integer getSameTimes() {
		return get("same_times");
	}

	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}

	public java.lang.String getLogo() {
		return get("logo");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setQrcodeUrl(java.lang.String qrcodeUrl) {
		set("qrcode_url", qrcodeUrl);
	}

	public java.lang.String getQrcodeUrl() {
		return get("qrcode_url");
	}

	public void setCurrentVideoId(java.lang.String currentVideoId) {
		set("current_video_id", currentVideoId);
	}

	public java.lang.String getCurrentVideoId() {
		return get("current_video_id");
	}

	public void setCurrentVideoTime(java.lang.String currentVideoTime) {
		set("current_video_time", currentVideoTime);
	}

	public java.lang.String getCurrentVideoTime() {
		return get("current_video_time");
	}

	public void setCurrentIsBack(java.lang.Integer currentIsBack) {
		set("current_is_back", currentIsBack);
	}

	public java.lang.Integer getCurrentIsBack() {
		return get("current_is_back");
	}


	public void setNeedPlayNext(java.lang.Integer needPlayNext) {
		set("need_play_next", needPlayNext);
	}

	public java.lang.Integer getNeedPlayNext() {
		return get("need_play_next");
	}

	public void setFriendsNum(java.lang.Integer friendsNum) {
		set("friends_num", friendsNum);
	}

	public java.lang.Integer getFriendsNum() {
		return get("friends_num");
	}

	public void setVideosNum(java.lang.Integer videosNum) {
		set("videos_num", videosNum);
	}

	public java.lang.Integer getVideosNum() {
		return get("videos_num");
	}


	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setLastChangeTime(java.util.Date lastChangeTime) {
		set("last_change_time", lastChangeTime);
	}

	public java.util.Date getLastChangeTime() {
		return get("last_change_time");
	}

	public void setManualName(String manualName){
		set("manual_name", manualName);
	}

	public String getManualName(){
		return get("manual_name");
	}

	public boolean saveOrUpdate(){
		Integer id=get("id");
		if(id==null){
			return save();
		}else{
			return super.update();
		}
	}

	public boolean superSave(){
		return super.save();
	}

}
