package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanDetail<M extends BasePlanDetail<M>> extends BaseModule<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setPlanId(java.lang.String planId) {
		set("plan_id", planId);
	}

	public java.lang.String getPlanId() {
		return get("plan_id");
	}

	public void setPlanDetail(java.lang.String planDetail) {
		set("plan_detail", planDetail);
	}

	public java.lang.String getPlanDetail() {
		return get("plan_detail");
	}

	public void setFinishPercentage(java.lang.Integer finishPercentage) {
		set("finish_percentage", finishPercentage);
	}

	public java.lang.Integer getFinishPercentage() {
		return get("finish_percentage");
	}

	public void setMarkTime(java.util.Date markTime) {
		set("mark_time", markTime);
	}

	public java.util.Date getMarkTime() {
		return get("mark_time");
	}

	public void setSortIndex(java.lang.Integer sortIndex) {
		set("sort_index", sortIndex);
	}

	public java.lang.Integer getSortIndex() {
		return get("sort_index");
	}

	public void setHasAnnex(java.lang.Integer hasAnnex) {
		set("has_annex", hasAnnex);
	}

	public java.lang.Integer getHasAnnex() {
		return get("has_annex");
	}

}
