package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAd<M extends BaseAd<M>> extends BaseModule<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAdUrl(java.lang.String adUrl) {
		set("ad_url", adUrl);
	}

	public java.lang.String getAdUrl() {
		return get("ad_url");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setStartDate(java.lang.String startDate) {
		set("start_date", startDate);
	}

	public java.lang.String getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.lang.String endDate) {
		set("end_date", endDate);
	}

	public java.lang.String getEndDate() {
		return get("end_date");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setModuleType(java.lang.String moduleType) {
		set("module_type", moduleType);
	}

	public java.lang.String getModuleType() {
		return get("module_type");
	}

	public void setSortIdx(java.lang.Integer sortIdx) {
		set("sort_idx", sortIdx);
	}

	public java.lang.Integer getSortIdx() {
		return get("sort_idx");
	}

	public void setLink(java.lang.String link) {
		set("link", link);
	}

	public java.lang.String getLink() {
		return get("link");
	}

}
