package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivityVideo<M extends BaseModule<M>> extends BaseModule<M> {

	public void setActivityId(java.lang.String activityId) {
		set("activity_id", activityId);
	}

	public java.lang.String getActivityId() {
		return get("activity_id");
	}

	public void setVideoId(java.lang.String videoId) {
		set("video_id", videoId);
	}

	public java.lang.String getVideoId() {
		return get("video_id");
	}

	public void setPlayStatus(java.lang.String playStatus) {
		set("play_status", playStatus);
	}

	public java.lang.String getPlayStatus() {
		return get("play_status");
	}

	public void setPlayIdx(java.lang.String playIdx) {
		set("play_idx", playIdx);
	}

	public java.lang.String getPlayIdx() {
		return get("play_idx");
	}

	public void setInsertType(java.lang.String insertType) {
		set("insert_type", insertType);
	}

	public java.lang.String getInsertType() {
		return get("insert_type");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

}
