package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanNoticeStatus<M extends BasePlanNoticeStatus<M>> extends BaseModule<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setNoticeId(java.lang.String noticeId) {
		set("notice_id", noticeId);
	}

	public java.lang.String getNoticeId() {
		return get("notice_id");
	}

	public void setReadStatus(java.lang.String readStatus) {
		set("read_status", readStatus);
	}

	public java.lang.String getReadStatus() {
		return get("read_status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
