package com.guima.domain;

import com.guima.base.model.BaseModule;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScoreRecord<M extends BaseScoreRecord<M>> extends BaseModule<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreateFullTime(java.util.Date createFullTime) {
		set("create_full_time", createFullTime);
	}

	public java.util.Date getCreateFullTime() {
		return get("create_full_time");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateDate(java.lang.String createDate) {
		set("create_date", createDate);
	}

	public java.lang.String getCreateDate() {
		return get("create_date");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setScoreMessage(java.lang.String scoreMessage) {
		set("score_message", scoreMessage);
	}

	public java.lang.String getScoreMessage() {
		return get("score_message");
	}

}
