package com.guima.domain;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanCalendar<M extends BasePlanCalendar<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateNum(java.lang.Integer createNum) {
		set("create_num", createNum);
	}

	public java.lang.Integer getCreateNum() {
		return get("create_num");
	}

	public void setFinishedNum(java.lang.Integer finishedNum) {
		set("finished_num", finishedNum);
	}

	public java.lang.Integer getFinishedNum() {
		return get("finished_num");
	}

	public void setUnfinishedNum(java.lang.Integer unfinishedNum) {
		set("unfinished_num", unfinishedNum);
	}

	public java.lang.Integer getUnfinishedNum() {
		return get("unfinished_num");
	}

}
