package com.guima.domain;

import com.guima.kits.Constant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config();

	public Config(String text,String image,String type){
		setType(type);
		setImage(image);
		setText(text);
		setStatus(Constant.ACTIVE);
	}

	public Config(){

	}

}
