package com.guima.domain;

import com.guima.domain.BaseCustomUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomUser extends BaseCustomUser<CustomUser> {
	public static final CustomUser dao = new CustomUser();

	public CustomUser(){

	}

	public CustomUser(String id,String name,String headerUrl,String desc,String token){
		setHeaderUrl(headerUrl);
		setName(name);
		setId(id);
		setDesc(desc);
		setToken(token);
	}

}
