package com.guima.domain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
	public static final Dictionary dao = new Dictionary();

	public Dictionary(String name,String type,Integer sortIdx,Integer isBackground){
		this.setName(name);
		this.setType(type);
		this.setSortIdx(sortIdx);
		this.setIsBackground(isBackground);
	}

	public Dictionary(){
		super();
	}

	public void  getMusicTheme(){

	}
}
