package com.guima.domain;

import com.guima.domain.BaseDoLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DoLike extends BaseDoLike<DoLike> {
	public static final DoLike dao = new DoLike();
}
