package com.guima.domain;

import com.guima.domain.BaseInterfaceConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterfaceConfig extends BaseInterfaceConfig<InterfaceConfig> {
	public static final InterfaceConfig dao = new InterfaceConfig();
}
