package com.guima.domain;

import com.guima.domain.BasePlanAnnex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanAnnex extends BasePlanAnnex<PlanAnnex> {
	public static final PlanAnnex dao = new PlanAnnex();
}
