package com.guima.domain;

import com.guima.domain.BasePlan;
import com.guima.enums.ConstantEnum;
import com.guima.kits.Constant;

import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plan extends BasePlan<Plan> {


	String statusDesc;

	boolean isOverdue;

	String endDateDesc;


	public static final Plan dao = new Plan();


	public void init(String title,String creator,Date createTime ,Date endDate,
			String privacy,Date startDate){
		this.setTitle(title);
		setCreator(creator);
		setCreateTime(createTime);
		setEndDate(endDate);
		setIsDeleted(Constant.IS_DELETED_NO);
		setPrivacy(privacy);
		setStartDate(startDate);
		setStatus(ConstantEnum.STATUS_ONGOING.getValue());
	}

	public String getEndDateDesc() {
		return endDateDesc;
	}

	public void setEndDateDesc(String endDateDesc) {
		this.endDateDesc = endDateDesc;
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}


	public boolean isOverdue() {
		return isOverdue;
	}

	public void setOverdue(boolean overdue) {
		isOverdue = overdue;
	}
}
