package com.guima.domain;

import com.guima.domain.BasePlanNoticeStatus;
import com.guima.kits.Constant;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanNoticeStatus extends BasePlanNoticeStatus<PlanNoticeStatus> {
	public static final PlanNoticeStatus dao = new PlanNoticeStatus();

	public void init(String creator,String noticeId){
		this.setCreator(creator);
		this.setNoticeId(noticeId);
		this.setCreateTime(new Date());
		this.setReadStatus(Constant.ACTIVE);

	}
}
