package com.guima.domain;

import com.guima.domain.BasePlanComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanComment extends BasePlanComment<PlanComment> {
	public static final PlanComment dao = new PlanComment();
}
