package com.guima.domain;

import com.guima.domain.BasePlanNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanNotice extends BasePlanNotice<PlanNotice> {
	public static final PlanNotice dao = new PlanNotice();
}
