package com.guima.domain;

import com.guima.domain.BasePlanNotice;
import com.guima.kits.Constant;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanNotice extends BasePlanNotice<PlanNotice> {
	public static final PlanNotice dao = new PlanNotice();

	public void init(String title,String type,String receiverType,String content,String createDate,String endDate){
		setTitle(title);
		setType(type);
		setReceiverType(receiverType);
		setContent(content);
		setCreateDate(createDate);
		setEndDate(endDate);
		setIsDeleted(Constant.IS_DELETED_NO);
	}
}
