package com.guima.domain;

import com.guima.domain.BasePlanDetailAnnex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanDetailAnnex extends BasePlanDetailAnnex<PlanDetailAnnex> {
	public static final PlanDetailAnnex dao = new PlanDetailAnnex();
}
