package com.guima.domain;

import com.guima.domain.BasePlanCalendar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanCalendar extends BasePlanCalendar<PlanCalendar> {
	public static final PlanCalendar dao = new PlanCalendar();
}
