package com.guima.domain;

import com.guima.domain.BasePlanNoticeStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanNoticeStatus extends BasePlanNoticeStatus<PlanNoticeStatus> {
	public static final PlanNoticeStatus dao = new PlanNoticeStatus();
}
