package com.guima.domain;

import com.guima.domain.BasePlanComment;
import com.guima.kits.Constant;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanComment extends BasePlanComment<PlanComment> {
	public static final PlanComment dao = new PlanComment();

	public PlanComment(){

	}

	public PlanComment(String comment,String creatorId,String planId){
		this.setComment(comment);
		this.setCreateTime(new Date());
		this.setCreatorId(creatorId);
		this.setIsDeleted(Constant.IS_DELETED_NO);
		this.setPlanId(planId);
		this.setMarkDeleted(Constant.MARK_ZERO);
	}
}
