package com.guima.domain;

import com.guima.domain.BasePlanCreateNum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanCreateNum extends BasePlanCreateNum<PlanCreateNum> {
	public static final PlanCreateNum dao = new PlanCreateNum();
}
