package com.guima.domain;

import com.guima.domain.BaseScoreRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScoreRecord extends BaseScoreRecord<ScoreRecord> {
	public static final ScoreRecord dao = new ScoreRecord();
}
