package com.guima.domain;

import com.guima.kits.Constant;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sign extends BaseSign<Sign> {
	public static final Sign dao = new Sign();

	public Sign() {
	}


	public void init(String creatorHeaderUrl, String creator, String creatorName, String describer,
					 String privacy, String photoUrl){
		setCreatorHeaderUrl(creatorHeaderUrl);
		setCreator(creator);
		setCreatorName(creatorName);
		setDescriber(describer);
		setIsDeleted(Constant.IS_DELETED_NO);
		setPhotoUrl(photoUrl);
		setPrivacy(privacy);
		setCreateTime(new Date());
	}
}
