package com.guima.domain;

import com.guima.domain.BaseSinger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Singer extends BaseSinger<Singer> {
	public static final Singer dao = new Singer();
}
