package com.guima.domain;

import com.guima.domain.BaseUser;
import com.guima.kits.Constant;
import com.guima.kits.Kit;

import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public void init(String openId,String name,String headerUrl,String city,
					 String country,String lanuage,String gender,String province,String sessionKey,String unionId){
		String id=UUID.randomUUID().toString();
		this.setId(id);
		this.setOpenId(openId);
		this.setName(name);
		this.setHeaderUrl(headerUrl);
		this.setCity(city);
		this.setCountry(country);
		this.setLanguage(lanuage);
		this.setGender(gender);
		this.setToken(Kit.MD5(id + "" + openId));
		this.setProvince(province);
		this.setSessionKey(sessionKey);
		this.setUnionid(unionId);
		this.setStatus(Constant.ACTIVE);
		this.setBanned(Constant.MARK_ZERO);
	}
}
