package com.guima.domain;

import com.guima.domain.BaseUserActiveRecord;

import java.util.UUID;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserActiveRecord extends BaseUserActiveRecord<UserActiveRecord> {
	public static final UserActiveRecord dao = new UserActiveRecord();

	public UserActiveRecord(){

	}

	public UserActiveRecord(String userId,String date){
		this.setId(UUID.randomUUID().toString());
		this.setUserId(userId);
		this.setDate(date);
	}
}
