package com.guima.domain;

import com.guima.domain.BaseUserRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRecord extends BaseUserRecord<UserRecord> {
	public static final UserRecord dao = new UserRecord();
}
