package com.guima.domain;

import com.guima.domain.BaseYesOrNoQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YesOrNoQuestion extends BaseYesOrNoQuestion<YesOrNoQuestion> {
	public static final YesOrNoQuestion dao = new YesOrNoQuestion();
}
